[project]
name = "imod32"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pymodbus>=3.11.3",
    "pyserial>=3.5",
    "serial>=0.0.97",
]
