[project]
name = "imod32"
version = "0.1.0"
description = "This software handle data management between modbus sensor and web app"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "paho-mqtt>=2.1.0",
    "pymodbus==3.8.0",
    "pyserial>=3.5",
]
